export const UPDATE_CART = 'update_cart'
export const UPDATE_USERINFO = 'update_userInfo'
export const UPDATE_BILLINFO = 'update_billInfo'
export const UPDATE_DISCOUNTINFO = 'update_discountInfo'
export const UPDATE_ORDERINFO = 'update_orderInfo'
